name: release


on:
  workflow_dispatch:
    inputs: 
      release:
        description: 'release version'
        required: true
        default: 'v1.0.2'
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'

      #todo 运行测试

      - name: import application certificate
        id: keychain
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - run: flutter config --enable-macos-desktop

      # flutter build macos 会自动运行 flutter pub get
      - name: build macos
        run: |
          tag=${{ github.ref_name }}
          version=${tag:1}
          number=`date +%Y%m%d%H%M%S`
          flutter build macos --build-name=$version --build-number=$number

      - name: "Notarize Release Build"
        uses: devbotsxyz/xcode-notarize@v1
        with:
          product-path: "build/macos/Build/Products/Release/public tools.app"
          appstore-connect-username: ${{ secrets.NOTARIZATION_USERNAME }}
          appstore-connect-password: ${{ secrets.NOTARIZATION_PASSWORD }}

      - name: zip *.app
        run: ditto -c -k --sequesterRsrc --keepParent "build/macos/Build/Products/Release/public tools.app" "build/macos/Build/Products/Release/public tools.zip"

      - uses: actions/upload-artifact@v2
        with:
          name: build-app
          path: "build/macos/Build/Products/Release/public tools.zip"
      
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: install deps
        run: pnpm install

      - name: bulild store.json
        run: pnpm run build-store

      - name: deploy store
        run: pnpm run deploy-store

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/macos/Build/Products/Release/public tools.zip,build/store.json"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
